<a href="https://colab.research.google.com/github/yleessam/tf/blob/main/perceptron_and_%EB%B0%B0%ED%8F%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 임포트 하기

In [ ]:
import numpy as np

## NumPy 란?

[Numpy](https://numpy.org/)
- “Numerical Python”의 줄임 말로 수치계산을 쉽고 빠르게 다루는 파이썬 라이브러리
- 행렬과 벡터 연산을 위한 사실상의 표준 라이브러리
- 고성능 다차원 배열(ndarray) 객체와 이러한 배열들과 함께 작동하는 도구들을 제공

- Numpy의 장점은 빠른 처리 속도와  정교한 Broadcasting
  - C로 작성
  - 리스트와 메모리 저장구조 다름 - 연속된 메모리에 저장
  - 반복문을 사용하지 않고 배열로 바로 계산
- 선형대수, 난수 생성, 푸리에 변환 기능 지원
- 머신러닝에서 이미지,영상, 텍스트, 소리등의 모든 데이터는 실수형태의 배열로 표현, 머신러닝을 위한 데이터 처리의 핵심 도구  
* C/C++및 포트란 등 다른 프로그래밍 언어로 쉽게 변환

In [ ]:
## X.shape 배열의 차원을 (m,n) 튜플로 표시
## np.ones 배열을 모두 1로 초기화
## np.c_ 두 배열을 가로 방향(왼쪽에서 오른쪽으로)으로 합치기
# X.shape 예제


# np.ones 예제

# np.c_ 예제


X.shape: (3, 2)
X.shape[0]: 3
ones_array:
 [[1. 1. 1.]
 [1. 1. 1.]]
combined_array:
 [[1 4]
 [2 5]
 [3 6]]


# 퍼셉트론 클래스

In [ ]:
class Perceptron:
    def __init__(self, N, alpha):# 생성자
        # 가중치 초기화: N개의 입력과 1개의 바이어스를 위한 N+1 크기의 가중치 배열 생성.


        # 학습률(learning rate) alpha 초기화

        print("Perceptron class created")

    def step(self, x):  # 활성화 함수 계단 함수(step function)


    def fit(self, X, y, epochs = 10):
        # X 데이터에 바이어스 항목을 추가. np.ones로 1로 채워진 열을 X에 추가함.


        # 지정된 에포크 수만큼 반복 학습.


    def predict(self, X):  # 예측 메서드
        # X를 최소 2차원 배열로 변환.

        # X에 바이어스 항목 추가.

        # 예측을 수행. 가중치와 입력값의 점곱을 계산 후 활성화 함수 적용.

        print('------------------')



가중치 업데이트 (Weight Update):

self.W += -self.alpha * error * x: 이 계산된 값을 현재 가중치 self.W에 더하여 가중치를 업데이트합니다.    
 음(-) 기호는 오류의 방향을 반대로 하여 가중치를 조정하는 데 사용됩니다.    
즉, 오류가 양수면 가중치를 줄이고, 오류가 음수면 가중치를 늘립니다.


# 퍼셉트론 클래스 객체 만들기

In [ ]:
per =

Perceptron class created


alpha가 0.9로 설정된 이유:

alpha는 학습률을 의미하며, 가중치를 얼마나 큰 단계로 조정할지 결정합니다.

# 퍼셉트론 학습(트레이닝) 하기

In [ ]:
X =
Y =
per.

# 예측하기

AND 논리: False AND False

In [ ]:
x =


0
------------------


AND 논리: True AND False

In [ ]:
x =


0
------------------


AND 논리: False AND True

In [ ]:
x =


0
------------------


AND 논리: True AND True

In [ ]:
x =



1
------------------
